Task1 part2 implement design
abood454/assigments pull request #2
Opened 2021-03-21 13:41 UTC by abood454

part 2

2021-03-21 20:50 UTC, ashrafabuodeh requested changes

2021-03-21 20:50 UTC, ashrafabuodeh commented on task_1/style.css
> +
remove space

2021-03-21 21:40 UTC, Mohsen-Awad requested changes

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/index.html
> +
remove space

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/index.html
> +                        <p style="margin: 0;"> View More</p>
put the style in css file

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/index.js
> + }
add new line at the end

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/style.css
> +    margin-top: 20px;
use shorthand margin

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/style.css
> +    margin-top: 5px;
use shorthand margin

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/style.css
> +    margin-top: 10px;
also use shorthand margin

2021-03-21 21:40 UTC, Mohsen-Awad commented on task_1/style.css
> +    margin-top: 50px;
use shorthand margin

2021-03-21 23:28 UTC, araraltawarah98 approved these changes

2021-03-22 18:43 UTC, laithyounes requested changes

2021-03-22 18:43 UTC, laithyounes commented on task_1/index.html
> +                    <img class="image" src="Assets/images/MOCHA LATE.png">
change image name/title this will not run as expected on some OS/browsers

2021-03-22 18:43 UTC, laithyounes commented on task_1/index.html
> +                        <p style="margin: 0;"> View More</p>
yes, let's not use inline styles

2021-03-22 18:43 UTC, laithyounes commented on task_1/index.html
> +                <p class="Des">Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species.</p>
class naming convention should be fixed here

2021-03-22 18:43 UTC, laithyounes commented on task_1/index.html
> +                <img class="image" src="./Assets/images/MOcha Late 02.png">
nit: let's change the class name here, image is too generic

2021-03-22 18:43 UTC, laithyounes commented on task_1/index.js
> + const MainEvent = (ID) => {
please use camelCase naming convention here

2021-03-22 18:43 UTC, laithyounes commented on task_1/style.css
> +#NavList {
nit: we can rely more on classes

2021-03-22 18:43 UTC, laithyounes commented on task_1/index.html
> +                    <p class="coffie-title">Mocha Late</p>
`coffie-title` typo

2021-03-22 19:27 UTC, laithyounes approved these changes

2021-03-22 19:49 UTC, ashrafabuodeh approved these changes

2021-03-22 22:04 UTC, Mohsen-Awad approved these changes

2021-03-23 07:59 UTC, araraltawarah98 approved these changes

2021-03-24 11:09 UTC, mmasaid commented on task_1/index.html
> +                <li id="profile-image" onclick="onclick_navbar_item('profile-image')"><img class="profile-size" src="./Assets/images/profile Image.png"></li>
Use kebab case for the all image, class, ids to be consistent  
```suggestion
                <li id="profile-image" onclick="onclick_navbar_item('profile-image')"><img class="profile-size" src="./Assets/images/profile-image.png"></li>
```

2021-03-24 11:10 UTC, mmasaid commented on task_1/index.html
> +                    <pre class="write">1 Bag                          $69.99</pre>
```suggestion
                    <pre class="item-price">1 Bag                          $69.99</pre>
```

2021-03-24 11:12 UTC, mmasaid commented on task_1/index.html
> +                        <img src="./Assets/images/Mocha-Late02.png" alt="Mocha Late">
names convention 
```suggestion
                        <img src="./Assets/images/mocha-late02.png" alt="Mocha Late">
```

2021-03-24 11:22 UTC, mmasaid commented on task_1/style.css
> +}
the color property missing depend on the class name 
```suggestion
.black-color {
    color: black;
    font-size: 40px;
    margin: 0;
}
```

2021-03-24 11:23 UTC, mmasaid commented on task_1/style.css
> +.Card {
```suggestion
.card {
```

2021-03-24 11:25 UTC, mmasaid commented on task_1/style.css
> +.write {
```suggestion
.item-price {
```

2021-03-24 11:27 UTC, mmasaid commented on task_1/style.css
> +    gap: 20px;
use margin instead 
```suggestion
    margin :....
```

2021-03-24 11:28 UTC, mmasaid requested changes
Please address the comments and let me know if you have any questions

2021-03-24 14:11 UTC, mmasaid approved these changes

2021-03-24 14:12 UTC, merged